/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Arms.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Arms.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="arms_armature">
          <primitive object={nodes.spine002} />
          <primitive object={nodes.ik_handL} />
          <primitive object={nodes.ik_handR} />
          <skinnedMesh name="arms" geometry={nodes.arms.geometry} material={materials.arms} skeleton={nodes.arms.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Arms.glb')
