/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Car5_Police.glb --transform 
Files: Car5_Police.glb [58.99KB] > /Users/bechera/Documents/3DHouse/public/police/Car5_Police-transformed.glb [10KB] (83%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Car5_Police-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Car5_Police.geometry} material={materials.car5_police_mat} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Car5_Police-transformed.glb')
