/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Chair.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Chair.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Chair_02.geometry} material={materials.Chair_02} position={[-13.016, 0.318, 7.447]} />
    </group>
  )
}

useGLTF.preload('/Chair.glb')
