/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Bookcase.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Bookcase.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bookcase_01.geometry} material={materials.Bookcase_01} position={[-15.342, 0.513, 2.852]} />
    </group>
  )
}

useGLTF.preload('/Bookcase.glb')
