/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 table.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/table.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_Table_Rectangle_01.geometry} material={materials['MasterMaterial.003']} />
    </group>
  )
}

useGLTF.preload('/table.glb')
