/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Dresser.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Dresser.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Chest_drawers_02.geometry} material={materials.Chest_drawers_02} position={[-18.349, 0.382, -0.161]} scale={0.443} />
      <mesh geometry={nodes.Chest_drawers_02002.geometry} material={materials.Chest_drawers_02} position={[-18.349, 0.625, -0.135]} scale={0.443} />
      <mesh geometry={nodes.Chest_drawers_02003.geometry} material={materials.Chest_drawers_02} position={[-18.349, 0.359, -0.135]} scale={0.443} />
      <mesh geometry={nodes.Chest_drawers_02004.geometry} material={materials.Chest_drawers_02} position={[-18.349, 0.086, -0.135]} scale={0.443} />
    </group>
  )
}

useGLTF.preload('/Dresser.glb')
