/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 desktop-2.glb --transform 
Files: desktop-2.glb [39.59KB] > /Users/bechera/Documents/3DHouse/public/desktop/desktop-2-transformed.glb [6.38KB] (84%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from "three";

export function Model(props : JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF('/desktop-2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={(nodes.Desktop as THREE.Mesh).geometry} material={materials.Material} position={[0, 0.221, -2.921]} />
    </group>
  )
}

useGLTF.preload('/desktop-2-transformed.glb')
