/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 fanshawe.glb --transform 
Files: fanshawe.glb [62.02KB] > /Users/bechera/Documents/3DHouse/public/Fanshawe/fanshawe-transformed.glb [7.45KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/fanshawe-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.628, -0.539]} rotation={[2.345, 0, 0]} scale={0.276}>
        <mesh geometry={nodes.Cube005.geometry} material={materials['red.002']} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['dark red.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/fanshawe-transformed.glb')
