/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Arms.glb 
*/

import { useRef, useEffect, useMemo } from "react";
import { useGraph, useThree } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import * as THREE from "three";
import { TextureLoader, NearestFilter, LinearMipMapLinearFilter } from "three";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF("Arms/Arms.glb");
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  // const { actions } = useAnimations(animations, group);

  // const { camera } = useThree(); // Access the scene's camera
  // const armRef = useRef<THREE.Group>(null!);

  // useEffect(() => {
  //   if (armRef.current) {
  //     // Set arms as a child of the camera, so they move with it
  //     camera.add(armRef.current);

  //     if (armRef.current !== undefined) {
  //       // Position the arms in front of the camera (adjust as needed)
  //       armRef.current.position.set(0, -0.5, -1); // Fine-tune position to make it look realistic
  //       armRef.current.rotation.set(0, 0, 0); // Adjust rotation if needed
  //     }

  //     return () => {
  //       camera.remove(armRef.current); // Cleanup: remove from camera on unmount
  //     };
  //   }
  // }, [camera]);

  useEffect(() => {
    // Loop through all materials and set NearestFilter for their textures
    Object.values(materials).forEach((material: THREE.Material) => {
      if (
        material instanceof THREE.MeshBasicMaterial ||
        material instanceof THREE.MeshStandardMaterial
      ) {
        if (material.map) {
          material.map.minFilter = THREE.NearestFilter;
          material.map.magFilter = THREE.NearestFilter;
          material.map.needsUpdate = true;
        }
      }
    });
  }, [materials]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="arms_armature">
          <primitive object={nodes.spine002} />
          <primitive object={nodes.ik_handL} />
          <primitive object={nodes.ik_handR} />
          <skinnedMesh
            name="arms"
            geometry={(nodes.arms as THREE.Mesh).geometry}
            material={materials.arms}
            skeleton={(nodes.arms as THREE.SkinnedMesh).skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Arms.glb");
