/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Bed.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export default function Model(props: any) {
  const { nodes, materials } = useGLTF("Bed/Bed.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={(nodes.bed_04 as THREE.Mesh).geometry}
        material={materials.bed_04}
        position={[-3.864, 0.254, 3.027]}
      />
    </group>
  );
}

useGLTF.preload("/Bed.gltf");
