/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 bicycle.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("Bike/Bicycle.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={(nodes.FrontWheel as THREE.Mesh).geometry}
        material={materials["Bicycle Mat"]}
        position={[0, 1.072, 0]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[-1, -0.04, -1]}
      />
      <mesh
        geometry={(nodes.TopBar as THREE.Mesh).geometry}
        material={materials["Bicycle Mat"]}
        position={[-0.131, 1.072, 0]}
        rotation={[-1.187, 0, 0]}
        scale={[0.034, 0.019, 0.034]}
      />
      <mesh
        geometry={(nodes.BackWheel as THREE.Mesh).geometry}
        material={materials["Bicycle Mat"]}
        position={[0, 1.072, 4]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[-1, -0.04, -1]}
      />
      <mesh
        geometry={(nodes.Pedals as THREE.Mesh).geometry}
        material={materials["Bicycle Mat"]}
        position={[0.001, 0.856, 1.94]}
        scale={[0.099, 0.034, 0.099]}
      />
      <mesh
        geometry={(nodes.Chain as THREE.Mesh).geometry}
        material={materials["Bicycle Mat"]}
        position={[0.175, 0.828, 2.191]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.359}
      />
      <mesh
        geometry={(nodes.FrontWheel001 as THREE.Mesh).geometry}
        material={materials["Bicycle Mat"]}
        position={[0, 1.072, 0]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[-1, -0.04, -1]}
      />
    </group>
  );
}

useGLTF.preload("/bicycle.glb");
