/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Bookcase.glb 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("Bookcase/Bookcase.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={(nodes.Bookcase_01 as THREE.Mesh).geometry}
        material={materials.Bookcase_01}
        position={[-15.342, 0.513, 2.852]}
      />
    </group>
  );
}

useGLTF.preload("/Bookcase.glb");
