/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cart.glb --transform 
Files: cart.glb [20.6KB] > /Users/bechera/Documents/3DHouse/public/Cart/cart-transformed.glb [8.36KB] (59%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from "three";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF('Cart/cart-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={(nodes.Cube_TT_checker_512x512_COLOR_GRID_0  as THREE.Mesh).geometry} material={materials.TT_checker_512x512_COLOR_GRID} position={[1.461, 3.003, -0.21]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/cart-transformed.glb')
