/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 CD.glb -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    CD_CD_0: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('CD/CD.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CD_CD_0.geometry} material={materials.material} position={[0,0,0]} rotation={[-Math.PI / 2, 0, 0.348]} scale={0.06} />
    </group>
  )
}

useGLTF.preload('/CD.glb')
