/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 circuit.glb --transform 
Files: circuit.glb [1.05MB] > /Users/bechera/Documents/3DHouse/public/circuit/circuit-transformed.glb [85.41KB] (92%)
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from "three";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF('Circuit/circuit-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={(nodes.Cube as THREE.Mesh).geometry} material={materials['Material.001']} scale={[0.149, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/circuit-transformed.glb')
