/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 coffeeCup.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("Coffee/coffeeCup.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={(nodes.Cylinder005 as THREE.Mesh).geometry}
        material={(nodes.Cylinder005 as THREE.Mesh).material}
        position={[-9.062, 0.108, 11.417]}
      />
    </group>
  );
}

useGLTF.preload("/coffeeCup.glb");
