/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 door.glb --transform 
Files: door.glb [128.09KB] > /Users/bechera/Documents/3DHouse/public/Door/door-transformed.glb [17.3KB] (86%)
Author: SaukrDev (https://sketchfab.com/SaukrDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-psx-hinged-door-4c195ed39f14418ba998eda8c3ce72a6
Title: Low Poly Psx Hinged door
*/
import * as THREE from "three";
import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props : JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF('Door/door-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={(nodes.Cube_Material_0 as THREE.Mesh).geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} scale={[0.506, 0.063, 1]} />
      <mesh geometry={(nodes.Cylinder001_Material016_0 as THREE.Mesh).geometry} material={materials['Material.016']} position={[-0.512, -0.593, -0.047]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.013, 0.013, 0.066]} />
    </group>
  )
}

useGLTF.preload('/door-transformed.glb')
