/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 fan.glb 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { useFrame } from "@react-three/fiber";
import { useRef } from "react";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("Fan/fan.glb");
  const ref = useRef<THREE.Mesh>(null);

  useFrame(() => {
    if (ref.current) {
      ref.current.rotation.y += 0.02;
    }
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={(nodes.Ceiling_Fan as THREE.Mesh).geometry}
        material={materials.Ceiling_Fan}
        position={[-16.621, 0.679, -3.858]}
        rotation={[0, Math.PI / 4, 0]}
        scale={0.797}
      />
      <mesh
        ref={ref}
        geometry={(nodes.Ceiling_Fan_Blades as THREE.Mesh).geometry}
        material={materials.Ceiling_Fan}
        position={[-16.621, 0.51, -3.858]}
        rotation={[-Math.PI, 0.478, -Math.PI]}
        scale={0.797}
      />
    </group>
  );
}

useGLTF.preload("/fan.glb");
