/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 floppy.glb --transform -t 
Files: floppy.glb [43.21KB] > /Users/bechera/Documents/3DHouse/public/Floppy/floppy-transformed.glb [4.94KB] (89%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Blank_Floppy_Disc_Blank_Floppy_Disk_0: THREE.Mesh
  }
  materials: {
    Blank_Floppy_Disk: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('Floppy/floppy-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Blank_Floppy_Disc_Blank_Floppy_Disk_0.geometry} material={materials.Blank_Floppy_Disk}  rotation={[0, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/floppy-transformed.glb')
