/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 fn.glb --transform 
Files: fn.glb [5.78KB] > /Users/bechera/Documents/3DHouse/public/FN/fn-transformed.glb [4.52KB] (22%)
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF('FN/fn-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={(nodes.Cube as THREE.Mesh).geometry} material={materials.Material} position={[0, 1.166, 0]} scale={[1, 1.324, 0.156]} rotation={[0, 1.4, 0]}/>
    </group>
  )
}

useGLTF.preload('/fn-transformed.glb')
