/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 garbage.glb 
*/

import { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("Garbage/garbage.glb");

  useEffect(() => {

    // Loop through all materials and set NearestFilter for their textures
    Object.values(materials).forEach((material: THREE.Material) => {
      if (
        material instanceof THREE.MeshBasicMaterial ||
        material instanceof THREE.MeshStandardMaterial
      ) {
        if (material.map) {
          material.map.minFilter = THREE.NearestFilter;
          material.map.magFilter = THREE.NearestFilter;
          material.map.needsUpdate = true;
        }
      }
    });

  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <group position={[-24.016, -1.921, 25.199]}>
        <mesh
        // ref={garbageContainerRef}
          geometry={(nodes.Cube178 as THREE.Mesh).geometry}
          material={materials["Material.010"]}
        />
        <mesh
        // ref={garbagePlasticRef}
          geometry={(nodes.Cube178_1 as THREE.Mesh).geometry}
          material={materials.Plastic}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/garbage.glb");
