/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 garbage.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("Garbage/garbage.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-24.016, -1.921, 25.199]}>
        <mesh
          geometry={(nodes.Cube178 as THREE.Mesh).geometry}
          material={materials["Material.010"]}
        />
        <mesh
          geometry={(nodes.Cube178_1 as THREE.Mesh).geometry}
          material={materials.Plastic}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/garbage.glb");
