/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 keyboard.glb --transform 
Files: keyboard.glb [106.97KB] > /Users/bechera/Documents/3DHouse/public/keyboard/keyboard-transformed.glb [10.97KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from "three";

export default function Model(props : JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF('keyboard/keyboard-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={(nodes.keyboard_Material006_0 as THREE.Mesh).geometry} material={materials['Material.006']} position={[-0.104, 0, 0.541]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.338, 0.106, 0.15]} />
    </group>
  )
}

useGLTF.preload('/keyboard-transformed.glb')
