/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 shelf.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Shelf_Desk_0: THREE.Mesh
  }
  materials: {
    ['Desk.001']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('Links/shelf.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Shelf_Desk_0.geometry} material={materials['Desk.001']} position={[-0.88, 1.366, 0.367]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.075, 0.371, 0.014]} />
    </group>
  )
}

useGLTF.preload('/shelf.glb')
