/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 magazines.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("Magazines/magazines.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={(nodes.Magazines as THREE.Mesh).geometry}
        material={materials.Entertainment}
        position={[13.803, 0.122, 6.368]}
        scale={0.48}
      />
    </group>
  );
}

useGLTF.preload("/magazines.glb");
