/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mario.glb --transform 
Files: mario.glb [12.94KB] > /Users/bechera/Documents/3DHouse/public/Mario/mario-transformed.glb [4.62KB] (64%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from "three";

export default function Model(props : JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF('Mario/mario-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={(nodes.Cube as THREE.Mesh).geometry} material={materials.Material} position={[0, 1.166, 0]} rotation={[0, 1.4, 0]} scale={[1, 0.845, 0.156]} />
    </group>
  )
}

useGLTF.preload('/mario-transformed.glb')
