/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 monitor.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("Monitor/monitor.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[10.044, 0.458, 6.73]} scale={0.375}>
        <mesh
          geometry={(nodes.TV_04_1 as THREE.Mesh).geometry}
          material={materials.Electronics}
        />
        <mesh
          geometry={(nodes.TV_04_2 as THREE.Mesh).geometry}
          material={materials.Emissor}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/monitor.glb");
