/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mouse.glb --transform 
Files: mouse.glb [95.16KB] > /Users/bechera/Documents/3DHouse/public/keyboard/mouse-transformed.glb [10.1KB] (89%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from "three";

export default function Model(props : JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF('keyboard/mouse-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={(nodes.mouse_Material007_0 as THREE.Mesh).geometry} material={materials['Material.007']} position={[0.445, 0, 0.547]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.117, 0.153, 0.163]} />
    </group>
  )
}

useGLTF.preload('/mouse-transformed.glb')
