/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 painting_5.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("Paint_5/painting_5.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-10.772, 0.734, 9.064]} scale={0.442}>
        <mesh
          geometry={(nodes.Paintings_06_1 as THREE.Mesh).geometry}
          material={materials.Wood_02}
        />
        <mesh
          geometry={(nodes.Paintings_06_2 as THREE.Mesh).geometry}
          material={materials.Paintings}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/painting_5.glb");
