/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 painting_4.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("Paint_4/painting_4.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-12.293, 1.659, 7.863]} scale={0.442}>
        <mesh
          geometry={(nodes.Paintings_03_1 as THREE.Mesh).geometry}
          material={materials.Wood_02}
        />
        <mesh
          geometry={(nodes.Paintings_03_2 as THREE.Mesh).geometry}
          material={materials.Paintings}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/painting_4.glb");
