/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 painting_2.glb 
*/

import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("Paint_2/painting_2.glb");

  useEffect(() => {
    // Loop through all materials and set NearestFilter for their textures
    Object.values(materials).forEach((material: THREE.Material) => {
      if (
        material instanceof THREE.MeshBasicMaterial ||
        material instanceof THREE.MeshStandardMaterial
      ) {
        if (material.map) {
          material.map.minFilter = THREE.NearestFilter;
          material.map.magFilter = THREE.NearestFilter;
          material.map.needsUpdate = true;
        }
      }
    });
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <group position={[-11.251, 0.72, 6.872]} scale={0.748}>
        <mesh
          geometry={(nodes.Paintings_1 as THREE.Mesh).geometry}
          material={materials.Wood_02}
        />
        <mesh
          geometry={(nodes.Paintings_2 as THREE.Mesh).geometry}
          material={materials.Paintings}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/painting_2.glb");
