/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 plant_4.glb 
*/

import React, { useEffect } from "react";
import { useGLTF, MeshWobbleMaterial, PointMaterial } from "@react-three/drei";
import * as THREE from "three";

export default function Particle() {
  return (
    <mesh>
      <sphereBufferGeometry args={[1, 32, 32]} />
      <PointMaterial
        transparent
        vertexColors
        size={20}
        sizeAttenuation={false}
        depthTest={false}
        toneMapped={false}
      />
    </mesh>
  );
}
