/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 plant_4.glb 
*/

import React from "react";
import { useGLTF, MeshWobbleMaterial } from "@react-three/drei";
import * as THREE from "three";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("Plant_4/plant_4.glb") as any;

  const texture =
    materials.Plants?.map || new THREE.TextureLoader().load("Plant/Plants.png");

  return (
    <group {...props} dispose={null}>
      <group position={[-9.795, -0.009, 4.915]}>
        <mesh
          geometry={(nodes.Plants_01_1 as THREE.Mesh).geometry}
          material={materials.Plaster_02}
        />
        <mesh
          geometry={(nodes.Plants_01_2 as THREE.Mesh).geometry}
          material={materials.Plants}
        >
          <MeshWobbleMaterial factor={0.1} map={texture} transparent={true} />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/plant_4.glb");
