/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 plant.glb 
*/

import React from "react";
import { useGLTF, MeshWobbleMaterial } from "@react-three/drei";
import * as THREE from "three";
export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("Plant/plant.glb") as any;

  const texture =
    materials.Plants?.map || new THREE.TextureLoader().load("Plant/Plants.png");

  return (
    <group {...props} dispose={null}>
      <group position={[-10.891, -0.065, 4.945]} scale={0.2}>
        <mesh
          geometry={(nodes.Plants_04_1 as THREE.Mesh).geometry}
          material={materials.Plaster_02}
        >
          {" "}
        </mesh>
        <mesh
          geometry={(nodes.Plants_04_2 as THREE.Mesh).geometry}
          material={materials.Plants}
        >
          <MeshWobbleMaterial factor={0.1} map={texture} transparent={true} />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/plant.glb");
