/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 radio.glb 
*/

import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("Radio/radio.glb");

  useEffect(() => {
    // Loop through all materials and set NearestFilter for their textures
    Object.values(materials).forEach((material: THREE.Material) => {
      if (
        material instanceof THREE.MeshBasicMaterial ||
        material instanceof THREE.MeshStandardMaterial
      ) {
        if (material.map) {
          material.map.minFilter = THREE.NearestFilter;
          material.map.magFilter = THREE.NearestFilter;
          material.map.needsUpdate = true;
        }
      }
    });
  }, [materials]);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={(nodes.Radio_01 as THREE.Mesh).geometry}
        material={materials.Electronics}
        position={[13.024, 0.234, 7.873]}
        rotation={[0, 1.571, 0]}
        scale={-0.163}
      />
    </group>
  );
}

useGLTF.preload("/radio.glb");
