/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 radio.glb 
*/

import { useEffect, useState, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import {
  Canvas,
  extend,
  useFrame,
  useThree,
  useLoader,
} from "@react-three/fiber";

// Define props type
interface SoundProps {
  url: string;
}

function Sound({ url }: SoundProps) {
  const sound = useRef<THREE.PositionalAudio>(null!);
  const { camera } = useThree();
  const [listener] = useState(() => new THREE.AudioListener());
  camera.add(listener);
  const buffer = useLoader(THREE.AudioLoader, url);

  useEffect(() => {
    if (sound.current) {
      sound.current.setBuffer(buffer);
      sound.current.setRefDistance(0.3);
      sound.current.setDirectionalCone(90, 180, 1);
      sound.current.setLoop(true);
      sound.current.play();

      // Attach the listener to the camera
      camera.add(listener);

      // Cleanup: Remove listener on unmount
      return () => {
        camera.remove(listener);
      };
    }
  }, [buffer, camera, listener]);

  return <positionalAudio ref={sound} args={[listener]} />;
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("Radio/radio.glb");

  useEffect(() => {
    // Loop through all materials and set NearestFilter for their textures
    Object.values(materials).forEach((material: THREE.Material) => {
      if (
        material instanceof THREE.MeshBasicMaterial ||
        material instanceof THREE.MeshStandardMaterial
      ) {
        if (material.map) {
          material.map.minFilter = THREE.NearestFilter;
          material.map.magFilter = THREE.NearestFilter;
          material.map.needsUpdate = true;
        }
      }
    });
  }, [materials]);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={(nodes.Radio_01 as THREE.Mesh).geometry}
        material={materials.Electronics}
        position={[13.024, 0.234, 7.873]}
        rotation={[0, 1.571, 0]}
        scale={-0.163}
      />
      <Sound url="../../public/Radio/zapsplat_musical_ice_cream_van_musical_chime_004_43592.mp3" />
    </group>
  );
}

useGLTF.preload("/radio.glb");
