/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 sofa.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { vertexShader } from "../../shaders/vertexShader";
import { fragmentShader } from "../../shaders/fragmentShader";
import { useBox } from "@react-three/cannon"; // Import Cannon.js hook
import shaderMaterialTransformer from "./../../shaders/shaderMaterialTransformer"

export default function Model(props: JSX.IntrinsicElements["group"]) {
  // const [ref, api] = useBox<THREE.Group>(() => ({
  //    mass: 4 ,
  //    args: [1, 3, 1], // Adjust the size based on the object
  //   //  rotation: [0, 0, 0],
  //   }))

  const { nodes, materials } = useGLTF("Sofa/sofa.glb");

  const sofaWoodRef = useRef<THREE.Mesh>(null!);
  const sofaMatRef = useRef<THREE.Mesh>(null!);

  useEffect(() => {
    const woodMaterial = materials.Wood_10 as THREE.MeshBasicMaterial; // Cast to appropriate type
    const fabricMaterial = materials.Fabric_11 as THREE.MeshBasicMaterial; // Cast to appropriate type
    // Create the ShaderMaterial for the TV frame (or model)

    // Loop through all materials and set NearestFilter for their textures
    Object.values(materials).forEach((material: THREE.Material) => {
      if (
        material instanceof THREE.MeshBasicMaterial ||
        material instanceof THREE.MeshStandardMaterial
      ) {
        if (material.map) {
          material.map.minFilter = THREE.NearestFilter;
          material.map.magFilter = THREE.NearestFilter;
          material.map.needsUpdate = true;
        }
      }
    });

    if (sofaWoodRef.current) {
      sofaWoodRef.current.material = shaderMaterialTransformer(woodMaterial,4);
    }
    if (sofaMatRef.current) {
      sofaMatRef.current.material = shaderMaterialTransformer(fabricMaterial,10);
    }
  }, [materials]);

  return (
    // <group {...props} dispose={null}  ref={ref}>
      <group position={[10.876, 0.177, -3.175]} {...props} dispose={null} >
  
        <mesh
          ref={sofaWoodRef}
          geometry={(nodes.Armchair_08_1 as THREE.Mesh).geometry}
          material={materials.Wood_10}
        />
        <mesh
          ref={sofaMatRef}
          geometry={(nodes.Armchair_08_2 as THREE.Mesh).geometry}
          material={materials.Fabric_11}
        />

      </group>
    // </group>
  );
}

useGLTF.preload("/sofa.glb");
