/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 table_breakable.glb -k 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

interface explodeMesh extends THREE.Mesh{
  originalPosition : THREE.Vector3
  directionVector : THREE.Vector3
}

export default function Table(props : JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF('explode_table/table_breakable.glb')
  const group = useRef<THREE.Group>(null!);

  useEffect(() => {
    if(group.current){
      const groupWorldPosition = new THREE.Vector3();
      group.current.getWorldPosition(groupWorldPosition)

      group.current.children.forEach(( value, index, array) => {
        const mesh = value as explodeMesh;
        mesh.originalPosition = mesh.position.clone();

        const meshWorldPosition = new THREE.Vector3()
        mesh.getWorldPosition(meshWorldPosition);

        mesh.directionVector = meshWorldPosition.clone().sub(groupWorldPosition).normalize();
      })
    }
  },[])
  
  return (
    <group {...props} dispose={null} ref={group}>
      <mesh name="original" geometry={(nodes.original as THREE.Mesh).geometry} material={materials.Wood_05} position={[1.708, 0.951, -3.896]} />
      {/* <mesh name="Cube200_cell" geometry={(nodes.Cube200_cell as THREE.Mesh).geometry} material={materials.Wood_05} position={[3.46, 0.954, -5.007]} />
      <mesh name="Cube200_cell001" geometry={(nodes.Cube200_cell001 as THREE.Mesh).geometry} material={materials.Wood_05} position={[0.14, 0.372, -4.902]} />
      <mesh name="Cube200_cell002" geometry={(nodes.Cube200_cell002 as THREE.Mesh).geometry} material={materials.Wood_05} position={[-0.031, 1.048, -4.957]} />
      <mesh name="Cube200_cell003" geometry={(nodes.Cube200_cell003 as THREE.Mesh).geometry} material={materials.Wood_05} position={[3.281, 0.397, -2.881]} />
      <mesh name="Cube200_cell004" geometry={(nodes.Cube200_cell004 as THREE.Mesh).geometry} material={materials.Wood_05} position={[0.149, 0.395, -2.973]} />
      <mesh name="Cube200_cell005" geometry={(nodes.Cube200_cell005 as THREE.Mesh).geometry} material={materials.Wood_05} position={[3.364, 0.412, -4.812]} />
      <mesh name="Cube200_cell006" geometry={(nodes.Cube200_cell006 as THREE.Mesh).geometry} material={materials.Wood_05} position={[1.707, 0.998, -3.897]} />
      <mesh name="Cube200_cell007" geometry={(nodes.Cube200_cell007 as THREE.Mesh).geometry} material={materials.Wood_05} position={[-0.049, 0.956, -4.999]} />
      <mesh name="Cube200_cell008" geometry={(nodes.Cube200_cell008 as THREE.Mesh).geometry} material={materials.Wood_05} position={[-0.041, 1.049, -2.848]} />
      <mesh name="Cube200_cell009" geometry={(nodes.Cube200_cell009 as THREE.Mesh).geometry} material={materials.Wood_05} position={[0.14, 0.369, -2.883]} />
      <mesh name="Cube200_cell010" geometry={(nodes.Cube200_cell010 as THREE.Mesh).geometry} material={materials.Wood_05} position={[3.32, 0.579, -4.856]} />
      <mesh name="Cube200_cell011" geometry={(nodes.Cube200_cell011 as THREE.Mesh).geometry} material={materials.Wood_05} position={[3.449, 1.044, -4.969]} />
      <mesh name="Cube200_cell012" geometry={(nodes.Cube200_cell012 as THREE.Mesh).geometry} material={materials.Wood_05} position={[3.37, 0.429, -2.879]} />
      <mesh name="Cube200_cell013" geometry={(nodes.Cube200_cell013 as THREE.Mesh).geometry} material={materials.Wood_05} position={[0.062, 0.372, -2.889]} />
      <mesh name="Cube200_cell014" geometry={(nodes.Cube200_cell014 as THREE.Mesh).geometry} material={materials.Wood_05} position={[-0.054, 0.96, -2.797]} />
      <mesh name="Cube200_cell015" geometry={(nodes.Cube200_cell015 as THREE.Mesh).geometry} material={materials.Wood_05} position={[0.849, 0.894, -3.455]} />
      <mesh name="Cube200_cell016" geometry={(nodes.Cube200_cell016 as THREE.Mesh).geometry} material={materials.Wood_05} position={[1.707, 0.998, -3.897]} />
      <mesh name="Cube200_cell017" geometry={(nodes.Cube200_cell017 as THREE.Mesh).geometry} material={materials.Wood_05} position={[3.276, 0.425, -4.812]} />
      <mesh name="Cube200_cell018" geometry={(nodes.Cube200_cell018 as THREE.Mesh).geometry} material={materials.Wood_05} position={[3.461, 1.04, -2.837]} />
      <mesh name="Cube200_cell019" geometry={(nodes.Cube200_cell019 as THREE.Mesh).geometry} material={materials.Wood_05} position={[2.959, 0.95, -4.423]} />
      <mesh name="Cube200_cell020" geometry={(nodes.Cube200_cell020 as THREE.Mesh).geometry} material={materials.Wood_05} position={[0.909, 0.827, -4.374]} />
      <mesh name="Cube200_cell021" geometry={(nodes.Cube200_cell021 as THREE.Mesh).geometry} material={materials.Wood_05} position={[3.366, 0.431, -2.974]} />
      <mesh name="Cube200_cell022" geometry={(nodes.Cube200_cell022 as THREE.Mesh).geometry} material={materials.Wood_05} position={[2.427, 0.854, -3.455]} />
      <mesh name="Cube200_cell023" geometry={(nodes.Cube200_cell023 as THREE.Mesh).geometry} material={materials.Wood_05} position={[3.281, 0.397, -4.905]} />
      <mesh name="Cube200_cell024" geometry={(nodes.Cube200_cell024 as THREE.Mesh).geometry} material={materials.Wood_05} position={[2.78, 0.859, -2.798]} />
      <mesh name="Cube200_cell025" geometry={(nodes.Cube200_cell025 as THREE.Mesh).geometry} material={materials.Wood_05} position={[1.018, 0.942, -3.117]} />
      <mesh name="Cube200_cell026" geometry={(nodes.Cube200_cell026 as THREE.Mesh).geometry} material={materials.Wood_05} position={[1.707, 0.998, -3.897]} />
      <mesh name="Cube200_cell028" geometry={(nodes.Cube200_cell028 as THREE.Mesh).geometry} material={materials.Wood_05} position={[0.061, 0.395, -4.812]} />
      <mesh name="Cube200_cell029" geometry={(nodes.Cube200_cell029 as THREE.Mesh).geometry} material={materials.Wood_05} position={[2.427, 0.854, -4.418]} />
      <mesh name="Cube200_cell030" geometry={(nodes.Cube200_cell030 as THREE.Mesh).geometry} material={materials.Wood_05} position={[3.397, 0.729, -3.108]} />
      <mesh name="Cube200_cell031" geometry={(nodes.Cube200_cell031 as THREE.Mesh).geometry} material={materials.Wood_05} position={[3.467, 0.956, -2.79]} />
      <mesh name="Cube200_cell032" geometry={(nodes.Cube200_cell032 as THREE.Mesh).geometry} material={materials.Wood_05} position={[0.024, 0.724, -3.095]} />
      <mesh name="Cube200_cell033" geometry={(nodes.Cube200_cell033 as THREE.Mesh).geometry} material={materials.Wood_05} position={[0.149, 0.426, -4.812]} />
      <mesh name="Cube200_cell034" geometry={(nodes.Cube200_cell034 as THREE.Mesh).geometry} material={materials.Wood_05} position={[3.158, 0.875, -4.783]} />
      <mesh name="Cube200_cell035" geometry={(nodes.Cube200_cell035 as THREE.Mesh).geometry} material={materials.Wood_05} position={[0.061, 0.42, -2.971]} />
      <mesh name="Cube200_cell036" geometry={(nodes.Cube200_cell036 as THREE.Mesh).geometry} material={materials.Wood_05} position={[3.276, 0.395, -2.973]} />
      <mesh name="Cube200_cell037" geometry={(nodes.Cube200_cell037 as THREE.Mesh).geometry} material={materials.Wood_05} position={[3.369, 0.409, -4.903]} />
      <mesh name="Cube200_cell038" geometry={(nodes.Cube200_cell038 as THREE.Mesh).geometry} material={materials.Wood_05} position={[0.05, 0.743, -4.906]} />
      <mesh name="Cube200_cell039" geometry={(nodes.Cube200_cell039 as THREE.Mesh).geometry} material={materials.Wood_05} position={[0.066, 0.353, -4.895]} />
      <mesh name="Cube200_cell040" geometry={(nodes.Cube200_cell040 as THREE.Mesh).geometry} material={materials.Wood_05} position={[0.105, 0.579, -2.929]} />
      <mesh name="Cube200_cell041" geometry={(nodes.Cube200_cell041 as THREE.Mesh).geometry} material={materials.Wood_05} position={[0.105, 0.579, -4.856]} />
      <mesh name="Cube200_cell042" geometry={(nodes.Cube200_cell042 as THREE.Mesh).geometry} material={materials.Wood_05} position={[3.32, 0.579, -2.929]} />
      <mesh name="Cube200_cell043" geometry={(nodes.Cube200_cell043 as THREE.Mesh).geometry} material={materials.Wood_05} position={[3.405, 0.59, -2.845]} /> */}
    </group>
  )
}

useGLTF.preload('/table_breakable.glb')

