/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 tv_table.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import shaderMaterialTransformer from "./../../shaders/shaderMaterialTransformer"

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("TTable/tv_table.glb");

  const tvRef = useRef<THREE.Mesh>(null!);

  useEffect(() => {
    const tvMaterial = materials.Wood_05 as THREE.MeshBasicMaterial; // Cast to appropriate type

    // Loop through all materials and set NearestFilter for their textures
    Object.values(materials).forEach((material: THREE.Material) => {
      if (
        material instanceof THREE.MeshBasicMaterial ||
        material instanceof THREE.MeshStandardMaterial
      ) {
        if (material.map) {
          material.map.minFilter = THREE.NearestFilter;
          material.map.magFilter = THREE.NearestFilter;
          material.map.needsUpdate = true;
          material.shadowSide = THREE.DoubleSide
        }
      }
    });

    if (tvRef.current) {
      tvRef.current.material = shaderMaterialTransformer(tvMaterial, 5);
    }
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={tvRef}
        
        geometry={(nodes.Cube200 as THREE.Mesh).geometry}
        material={materials.Wood_05}
        position={[-12.94, -1.476, 3.233]}
      />
    </group>
  );
}

useGLTF.preload("/tv_table.glb");
