/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 phone.glb --transform 
Files: phone.glb [67.85KB] > /Users/bechera/Documents/3DHouse/public/Phone/phone-transformed.glb [19KB] (72%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/phone-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0, 0.179, 0]} scale={[0.99, 2.207, 2.207]}>
          <primitive object={nodes.Bone} />
        </group>
        <skinnedMesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.001']} skeleton={nodes.Cube.skeleton} position={[0, 0.179, 0]} scale={[0.99, 2.207, 2.207]} />
        <skinnedMesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.001']} skeleton={nodes.Cube001.skeleton} position={[0, 0.179, 0]} scale={[0.99, 2.207, 2.207]} />
      </group>
    </group>
  )
}

useGLTF.preload('/phone-transformed.glb')
